project:
  type: website
  output-dir: docs

website:
  title: "Bike Geometry Project"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Intro"
        contents:
          - index.qmd
      - section: "Gravel"
        contents:
          - qmd/gravel_tree.qmd
          - qmd/gravel_class.qmd
          - qmd/gravel_scatter.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

